{% set name = "molmod" %}
{% set version = "1.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3147eec3a57da164415359188a02385b9285486e70e98f9fc8e2d03037a8ffe3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy >=1.0
    - cython >=0.24.1
    - future
    - setuptools
  run:
    - python
    - pip
    - cython >=0.24.1
    - future
    - setuptools
    - {{ pin_compatible("numpy") }}

test:
  imports:
    - molmod
  commands:
    - pip check

about:
  home: http://molmod.github.io/molmod
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: MolMod is a collection of molecular modelling tools for python.

  description: |
    MolMod is a collection of molecular modelling tools for python. It is 
    used by other software developed at the CMM, including Yaff, TAMkin 
    and Zeobuilder.
  doc_url: http://molmod.github.io/molmod/
  dev_url: https://github.com/molmod/molmod

extra:
  recipe-maintainers:
    - jan-janssen
    - tovrstra
    - lvduyfhu
