travis:
  secure:
    BINSTAR_TOKEN: BHb12lgtv57FhJpo8e7uw7LHlsbC+z9r+DIrMh+/825DW8HvbmKylP4I6zlkwBErRb6Ok/hl96x+dIaFjtoEZdIxTjmVWPUMtVh3qeUPEcU816mS8LAw1tgNuHwkukrM47rsqtuIZQiS8jERTywEDa76tvPhTuOmNrqh7emxagEIyVhmHV2jTchS1O6l4Gufg5nDjUcOWji+8SFZnV+QHwc/iSHxEkYnHGuZ8mHnbdVL+VPPcirmoY4BQZXd9kG41pL2WID9sMNEAppE8Dam2ml0n3arnGz4Ln1zWk6W2VIS/z9W8UybfrdM2KDc8jYOFzG9SUE7VTj7YEbjWiAzv34r/b/P/lcvPDfpAiCkIrnXdXhSHLbWJVgoJOGray706E2I+r4QqBSAsZ+n2pQZSsnN4ge/HdTS0KrZ2R1RVKhZCL4pt8HEc1b70lt4PkGmQQzqMMd4Bqnrj6/ZY5UKgPfWEPM6ufyfv31PQjU5EBBjgPwIXvlQnpAZBWlZNqd/Rpu2W0KmG3VTjWK+oaXH1xvbjg2znK1wVGGPdQRzJJgOmtJSP5mDSWd0E7+ta989yDdJLg1Fm1Q7aXoQ3P9B3Fk5D414iuZv+wHIba0+4tJkLUHLxKBSuSf75YpeHzEnIBF2jETqlHrIUqI/kaKJTzUC9JJgrWF3hrqdT3g/zpI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
bot:
  automerge: true
